### ISSUE TITLE
Work Packages

### ISSUE THREAD

**Issue by abruch666** [fstreun/VS_Project#4]
Breakdown the work to subtasks to meet the project re-
quirements. Define and describe these tasks.
• WP1: XYZ . . .
• WP2: Set and Configuring Backend Serve . . .
• WP3: Integration . . .
• WPx: . . .
Stick to a concise, scientific writing style.

**Comment by abruch666** [comment]
SessionPublishService
DataSyncService
SessionChainBlock
Fincance

**Comment by abruch666** [comment]
Done with my part

**Comment by ggjini1** [comment]
Done with my part. You guys should look it through and tell me/us if anything interferes with some of your other plans.

**Comment by ggjini1** [comment]
Well, it seems like fabio already did my part :2nd_place_medal:

**Comment by fstreun** [comment]
so that you could help me finding requirements.

**Comment by abruch666** [comment]
done (but read over it after the system overview part has been done)
