### ISSUE TITLE
Milestones

### ISSUE THREAD

**Issue by abruch666** [fstreun/VS_Project#5]
The milestones section provides a work plan for carrying out the project. This is your schedule for getting the project done. Clearly state how the work packages will be distributed among the team members.

**Comment by ggjini1** [comment]
Done with my part. You guys should look it through and tell me/us if anything interferes with some of your other plans.

**Comment by fstreun** [comment]
since we are developing the data sharing part independent from the finance part (and vice versa) a finance milestone should be set before finishing the data sharing part.

**Comment by fstreun** [comment]
And maybe also split up different finance milestones: like conceptual, firsts tests, implementation with share data, second tests.

And also add testing to it.

**Comment by abruch666** [comment]
done
(but check again at the end)
